// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/api/pokemon.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/pokemon/[name].tsx";
import * as $4 from "./routes/search/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Header.tsx";
import * as $$2 from "./islands/PokeSearch.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/api/pokemon.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/pokemon/[name].tsx": $3,
    "./routes/search/index.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Header.tsx": $$1,
    "./islands/PokeSearch.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
